### ISSUE TITLE
Layouts 1 and 3 don't always work

### ISSUE THREAD

**Issue by ngregoire** [Ovi3/burp-menu-level#1]
Hello, I tried the extension on a Repeater request with Burp Suite Pro Early Adopter 2023.12.1.2 and a single loaded extension, Hackvertor. Under this setup, only layouts 4 (the default one) and 2 work. For layouts 1 and 3, the contextual menu doesn't appear anymore.

**Comment by Ovi3** [comment]
fixed. please check it https://github.com/Ovi3/burp-menu-level/releases/tag/v1.1
